---
title: "Late Join Guidelines"
toc: true
draft: true
---

Last updated: 2024-08-29

**Welcome to IS 310: Computing in the Humanities**

If you have joined the class after the first meeting, this page is for you. Please read it carefully and reach out to the Instructor if you have any questions.

## Getting Up to Speed

At our first class, we talked through the syllabus, which is available here on this website or as a Google Doc on Canvas. You should review the full syllabus and reach out to the Instructor if you have any questions. The recommended order for readings is:

- [Course Description](index.qmd)
- [Assessments and Assignments](assessments/index.qmd)
- [Course Policies](policies.qmd)
- [Weekly Schedule](schedule/index.qmd)

In particular, you should make sure that you understand the core goals of this course, the expectations and logistics for assignments (particularly the semester-long project), and our course policies around communication and AI.

## Catching Up on Materials & Assignments

In the second class of our first week, we covered three lessons:

1. [Course Tools & Software](materials/introducing-humanities-computing/01-course-tools.qmd), which covers all the tools and software we will be using in this course and provides instructions on how to get your computer setup and signed up for all relevant tools. If you have any issues with this, please reach out to the Instructor.
2. [Introduction to the Command Line & Prompt Engineering](materials/introducing-humanities-computing/02-intro-cli-prompt-engineering.qmd), which covers the basics of the command line and prompt engineering with AI Chatbots. You should read through the materials, and complete the exercises to the best of your ability.
3. [Introduction to Versioning & Git](materials/introducing-humanities-computing/03-intro-versioning-git.qmd), which covers the basics of versioning and Git. You should read through the materials, and complete the homework assignment to the best of your ability.

We have also read and discussed the following articles:

1. [Readings for the Programming & Processing Module](schedule/02-programming-and-processing.qmd). You should read through these articles for your own understanding.

Finally, please complete the following assignments:

1. [Initial Interest Survey](schedule/03-histories-of-culture-and-computing.qmd). This survey is available on Canvas and should be completed by the due date.

Hopefully this guide will help, but again, please reach out to the Instructor if you have any questions.
