---
title: "How Will We Work in This Course? Programming and Processing"
toc: true
date: 2026-01-22
---

## In-Class Agenda

- [ ] Discuss the assigned readings.
- [ ] Continue working through the Introduction to [Course Tools](../materials/introducing-humanities-computing/01-course-tools/index.qmd) and answer any questions (though this is primarily to be completed outside of class).
- [ ] Start [Introduction to the Command Line & Prompt Engineering](../materials/introducing-humanities-computing/02-intro-cli-prompt-engineering/index.qmd) and [Introduction to Versioning & Git](../materials/introducing-humanities-computing/03-intro-versioning-git/index.qmd) (if not completed in-class, these will become homework).

## Assigned Materials

**No Hypothesis Annotations Required for This Week**

- Buschek, Christo, and Jer Thorp. “Models All The Way Down.” *Knowing Machines*. [https://knowingmachines.org/models-all-the-way](https://knowingmachines.org/models-all-the-way)
- Vincent, Nick, and Hanlin Li. "GitHub Copilot and the Exploitation of 'Data Labor': A Wake-Up Call for the Tech Industry." *PSA Group* (blog), July 8, 2021. [https://www.psagroup.org/blogposts/101](https://www.psagroup.org/blogposts/101).
- Chin, Monica. "Kids Who Grew up with Search Engines Could Change STEM Education Forever." *The Verge*, September 22, 2021. [https://web.archive.org/web/20211102083237/https://www.theverge.com/22684730/students-file-folder-directory-structure-education-gen-z](https://web.archive.org/web/20211102083237/https://www.theverge.com/22684730/students-file-folder-directory-structure-education-gen-z). This is a web archive link because *The Verge* requires a subscription.
- Start Introduction to [Course Tools](../materials/introducing-humanities-computing/01-course-tools/index.qmd).

## Additional Materials (Not Required Reading)

- Chiang, Ted. "ChatGPT Is a Blurry JPEG of the Web." *The New Yorker*, February 9, 2023. [https://www.newyorker.com/tech/annals-of-technology/chatgpt-is-a-blurry-jpeg-of-the-web](https://www.newyorker.com/tech/annals-of-technology/chatgpt-is-a-blurry-jpeg-of-the-web).
- Schaul, Kevin, Szu Yu Chen, and Nitasha Tiku. "Inside the Secret List of Websites That Make AI like ChatGPT Sound Smart." *Washington Post*, April 19, 2023. [https://www.washingtonpost.com/technology/interactive/2023/ai-chatbot-learning/](https://www.washingtonpost.com/technology/interactive/2023/ai-chatbot-learning/)