---
title: "Histories of Culture & Computing"
toc: true
date: 2024-09-03
draft: true
---

## REVISED In-Class Agenda

**Unfortunately, Prof. LeBlanc has a family emergency and cannot attend class in person today. Class will instead be lead by TA, Jess Frye. Please note will there is not participation grades for discussion, there will be for the group activity.**

- [ ] Discuss the assigned readings is **now postponed until Thursday**.
- [ ] Short talk on career opportunities from the iSchool.
- [ ] Meet your group members and start working through the first group assignment [Mass Digitization & Digital Libraries](../collecting-digitizing-culture/index.qmd).
- [ ] Time permitting: Continue working through the [Introduction to Versioning & Git](../materials/introducing-humanities-computing/03-intro-versioning-git/index.qmd) and start reading through the [Advanced Git & GitHub](../materials/introducing-humanities-computing/05-advanced-git-github/index.qmd). Please contact Prof. LeBlanc via Discord if you have questions or difficulties with the materials, and we will be discussing them in class on Thursday.

## Assigned Materials

- Kahle, Brewster. "Universal Access to All Knowledge." *The American Archivist* 70, no. 1 (2007): 23-31. [https://www.jstor.org/stable/40294448](https://www.jstor.org/stable/40294448).
- Hennessey, Amardeep Singh and Kate. "African American Periodical Poetry (1900-1928) - Responsible Datasets in Context." *Responsible Datasets in Context*, July 1, 2024. [https://www.responsible-datasets-in-context.com/posts/african-american-periodical-poetry/aa-periodical-poetry.html?tab=data-essay](https://www.responsible-datasets-in-context.com/posts/african-american-periodical-poetry/aa-periodical-poetry.html?tab=data-essay). While you are encouraged to explore the entirety of this dataset, we will primarily be discussing the section "Where Did the Data Come From? Who Collected It?" in the data essay.

## Additional Materials

- Mcpherson, Tara. "Why Are the Digital Humanities So White?: Or Thinking the Histories of Race and Computation." In *Debates in the Digital Humanities*, edited by Matthew K. Gold, 139-60. University of Minnesota Press.

## Assignments

- Complete Initial Interest Survey (link available on Canvas)
