---
title: "Responsible Computing of Culture & Contextualizing Social Knowledge"
subtitle: "What does it mean to work with culture as data responsibly, and how does this change across disciplines and industries?"
toc: true
date: 2026-01-27
---

## In-Class Agenda

- Any questions from last week?
- Discuss LLMs as Research Tools and look at their data and survey [https://openreview.net/forum?id=p0BwJk3R1p#discussion](https://openreview.net/forum?id=p0BwJk3R1p#discussion)
- Discuss Myths of Generative AI
- Discuss Responsible Datasets in Context and Final Projects
- Start discussing focus with your groups, which are assigned [here](../assessments/04-groups.qmd) and the [GitHub Style Guide](../assessments/05-github-style-guide.qmd).

## Assigned Materials

- “Mission.” *Responsible Datasets in Context *(blog), n.d. [https://www.responsible-datasets-in-context.com/mission.html](https://www.responsible-datasets-in-context.com/mission.html) and discuss final projects
- Liao, Zhehui, Maria Antoniak, Inyoung Cheong, et al. “LLMs as Research Tools: A Large Scale Survey of Researchers’ Usage and Perceptions.” arXiv:2411.05025. Preprint, arXiv, October 30, 2024. [https://arxiv.org/html/2411.05025v1](https://arxiv.org/html/2411.05025v1).  
- Salvaggio, Eryk. 2024. “Challenging The Myths of Generative AI” *Tech Policy Press*, August 29. [https://techpolicy.press/challenging-the-myths-of-generative-ai](https://techpolicy.press/challenging-the-myths-of-generative-ai). 

## Assignments

- Complete Initial Interest Survey (link available on Canvas) due by January 21 at midnight.
