---
title: "Digital Objects & Obsolescence"
toc: true
date: 2024-09-10
draft: true
---

## In-Class Agenda

- [ ] Demo Hypothesis and review [updated instructions](../materials/introducing-humanities-computing/01-course-tools/index.qmd#how-to-annotate-with-hypothesis).
- [ ] Discuss the assigned readings.
- [ ] First group presentations on [Mass Digitization & Digital Libraries](../collecting-digitizing-culture/index.qmd).
- [ ] Time permitting: Introduction to [GitHub Style Guide & Project Management via GitHub Projects](../assessments/05-github-style-guide/index.qmd).
- [ ] Time permitting: work on group projects.

## Assigned Materials

- Johnson, Jessica Marie. "Markup Bodies: Black [Life] Studies and Slavery [Death] Studies at the Digital Crossroads." *Social Text* 36, no. 4 (137) (December 1, 2018): 57-79. [https://doi.org/10.1215/01642472-7145658](https://doi.org/10.1215/01642472-7145658). This reading is available on Canvas and please follow the [updated instructions on how to annotate local PDFs if you are using Hypothesis](../materials/introducing-humanities-computing/01-course-tools/index.qmd#using-hypothesis-on-local-pdfs).
- Keyes, Melanie Walsh and Os. "U.S. National Park Visit Data (1979-2023) - Responsible Datasets in Context." *Responsible Datasets in Context*, June 1, 2024. [https://www.responsible-datasets-in-context.com/posts/np-data/](https://www.responsible-datasets-in-context.com/posts/np-data/).

## Additional Materials

- Onuoha, Mimi. "The Library of Missing Datasets - MIMI ONUOHA." MIMI   ONUOHA. Accessed January 11, 2024. [https://mimionuoha.com/the-library-of-missing-datasets](https://mimionuoha.com/the-library-of-missing-datasets).
- Onuoha, Mimi. "MimiOnuoha/Missing-Datasets," January 9, 2024. [https://github.com/MimiOnuoha/missing-datasets](https://github.com/MimiOnuoha/missing-datasets).


### Additional Links

- *The Trans-Atlantic Slave Trade Database* [https://www.slavevoyages.org/](https://www.slavevoyages.org/).
- *Freedom on the Move* [https://freedomonthemove.org/](https://freedomonthemove.org/).
- *Enslaved: Peoples of the Historical Slave Trade* [https://enslaved.org/](https://enslaved.org/)

## Assignments

### Individual

- [ ] Complete [Init IS310 Homework](../materials/introducing-humanities-computing/03-intro-versioning-git/index.qmd#homework-init-is310).

### Group

- [ ] [Mass Digitization & Digital Libraries](../collecting-digitizing-culture/index.qmd) group assignment.
