---
title: "Histories of Culture & Computing"
subtitle: "How and when did we first start representing culture as data?"
toc: true
date: 2026-02-03
---

## In-Class Agenda

- [ ] Discuss the assigned readings.
- [ ] Start first group in-class assignment on [Digital Collections & Libraries](../assessments/06-collecting-digitizing-culture.qmd)
- [ ] Time permitting work on topic selection and review [Advanced GitHub and Git Features for working collaboratively](../materials/introducing-humanities-computing/05-advanced-git-github.qmd)

## Assigned Materials

Read the following:

- Kahle, Brewster. “Universal Access to All Knowledge.” *The American Archivist* 70, no. 1 (2007): 23–31. [https://www.jstor.org/stable/40294448](https://www.jstor.org/stable/40294448). Please follow the [instructions on how to annotate local PDFs if you are using Hypothesis](../materials/introducing-humanities-computing/01-course-tools/index.qmd#using-hypothesis-on-local-pdfs).
- Besser, Howard. “The Past, Present, and Future of Digital Libraries.” In *A Companion to Digital Humanities*. John Wiley & Sons, Ltd, 2004. [https://companions.digitalhumanities.org/DH/content/9781405103213_chapter_36.html](https://companions.digitalhumanities.org/DH/content/9781405103213_chapter_36.html) 

Explore the following:

- Hennessey, Amardeep Singh and Kate. “African American Periodical Poetry (1900-1928) – Responsible Datasets in Context.” *Responsible Datasets in Context*, July 1, 2024. [https://www.responsible-datasets-in-context.com/posts/african-american-periodical-poetry/aa-periodical-poetry.html?tab=data-essay](https://www.responsible-datasets-in-context.com/posts/african-american-periodical-poetry/aa-periodical-poetry.html?tab=data-essay). 

## Additional Materials

- Mcpherson, Tara. “Why Are the Digital Humanities So White?: Or Thinking the Histories of Race and Computation.” In Debates in the Digital Humanities, edited by Matthew K. Gold, NED-New edition., 139–60. University of Minnesota Press, 2012. [https://www.jstor.org/stable/10.5749/j.ctttv8hq.12](https://www.jstor.org/stable/10.5749/j.ctttv8hq.12).
- Section 2 Libraries and Database, Milligan, Ian. The Transformation of Historical Research in the Digital Age. Cambridge Elements in Historical Theory and Practice, August 2022. [https://doi.org/10.1017/9781009026055](https://doi.org/10.1017/9781009026055).
- Milic, Louis T. “The Next Step.” Computers and the Humanities 1, no. 1 (1966): 3–6. [http://www.jstor.org/stable/30199191](http://www.jstor.org/stable/30199191).


