---
title: "Data Feminism & Culture As Data"
toc: true
date: 2024-09-17
draft: true
---

## In-Class Agenda

- [ ] Discuss the assigned readings
- [ ] Group assignment on [Critical Cultural Data Explorations](../critical-cultural-data-explorations/index.qmd).
- [ ] Assign Project Manager for the week and start working on Group GitHub Repository.

## Assigned Materials

Two chapters from *Data Feminism* by Catherine D'Ignazio and Lauren F. Klein. Please click on the PDF link on each webpage to access the full chapter and annotate that pdf with Hypothesis:

- D'Ignazio, Catherine, and Lauren F. Klein. Chapter 1 "The Power Chapter." In *Data Feminism*. The MIT Press, 2020. [https://direct.mit.edu/books/book/4660/chapter/213285/The-Power-Chapter](https://direct.mit.edu/books/book/4660/chapter/213285/The-Power-Chapter).
- D'Ignazio, Catherine, and Lauren F. Klein. Chapter 4 "'What Gets Counted Counts.'" In *Data Feminism*, by Catherine D'Ignazio and Lauren F. Klein. The MIT Press, 2020. [https://direct.mit.edu/books/book/4660/chapter/213288/What-Gets-Counted-Counts](https://direct.mit.edu/books/book/4660/chapter/213288/What-Gets-Counted-Counts).

Another dataset to explore:

- Trejo, Sylvia Fernandez and Paulina Hernandez. "Gender Violence at the Border (1993-1998) - Responsible Datasets in Context." *Responsible Datasets in Context*, August 1, 2024. [https://www.responsible-datasets-in-context.com/posts/gender-violence/](https://www.responsible-datasets-in-context.com/posts/gender-violence/).

## Additional Materials

- Silge, Julia, Russell Samora, Amber Thomas, and Hanah Anderson. "She Giggles, He Gallops." *The Pudding*, August 2017. [https://pudding.cool/2017/08/screen-direction](https://pudding.cool/2017/08/screen-direction).
- Schmidt, Ben. "Gendered Language in Teaching Evaluations." [https://benschmidt.org/profGender/](https://benschmidt.org/profGender/).
- D'Ignazio, Catherine, and Lauren F. Klein. Chapter 6 "The Numbers Don't Speak for Themselves." In *Data Feminism*, 2020. [https://direct.mit.edu/books/oa-monograph/4660/chapter/213291/The-Numbers-Don-t-Speak-for-Themselves](https://direct.mit.edu/books/oa-monograph/4660/chapter/213291/The-Numbers-Don-t-Speak-for-Themselves).

### Additional Links

- [Pamphlet](https://cdn.theatlantic.com/media/mt/hua_hsu/barkhorn_womenvoters1.jpg) from Eleanor Barkhorn, "'Vote No on Women's Suffrage': Bizarre Reasons for Not Letting Women Vote," *Atlantic*, November 6, 2012, [https://www.theatlantic.com/sexes/archive/2012/11/vote-no-on-womens-suffrage-bizarre-reasons-for-not-letting-women-vote/264639/](https://www.theatlantic.com/sexes/archive/2012/11/vote-no-on-womens-suffrage-bizarre-reasons-for-not-letting-women-vote/264639/) cited in "The Power Chapter" of *Data Feminism*.
- Onuoha, Mimi. "The Library of Missing Datasets - MIMI ONUOHA." MIMI   ONUOHA. Accessed January 11, 2024. [https://mimionuoha.com/the-library-of-missing-datasets](https://mimionuoha.com/the-library-of-missing-datasets).
- Onuoha, Mimi. "MimiOnuoha/Missing-Datasets," January 9, 2024. [https://github.com/MimiOnuoha/missing-datasets](https://github.com/MimiOnuoha/missing-datasets).
- Schmidt, Ben. "Gendered Language in Teaching Evaluations." [https://benschmidt.org/profGender/](https://benschmidt.org/profGender/).
- *Colored Conventions Project* [https://coloredconventions.org/](https://coloredconventions.org/).
- *Saving Ukrainian Cultural Heritage Online* [https://www.sucho.org/](https://www.sucho.org/).
