---
title: "Digital Objects & Obsolescence"
subtitle: "What are the historic legacies and politics of representing culture as data?"
toc: true
date: 2026-02-10
---

## In-Class Agenda

- [ ] Discuss the assigned readings. Slides available [here](../slides/07-digital-objects-obsolescence.qmd).
- [ ] Groups present on [Mass Digitization & Digital Libraries Group Assignment](../assessments/06-collecting-digitizing-culture.qmd).

## Assigned Materials

Read:

- Johnson, Jessica Marie. “Markup Bodies: Black [Life] Studies and Slavery [Death] Studies at the Digital Crossroads.” Social Text 36, no. 4 (137) (December 1, 2018): 57–79. [https://doi.org/10.1215/01642472-7145658](https://doi.org/10.1215/01642472-7145658) (also available on Canvas)

Another dataset to explore:

- Keyes, Melanie Walsh and Os. “U.S. National Park Visit Data (1979-2023) – Responsible Datasets in Context,” June 1, 2024. [https://www.responsible-datasets-in-context.com/posts/np-data/?tab=data-essay](https://www.responsible-datasets-in-context.com/posts/np-data/?tab=data-essay). 

## Additional Materials & Links

- Rankin, Bill, and Matt Daniels. “Mapping Slavery Against US Incarceration.” *The Pudding*, January 2017. [https://pudding.cool/2017/01/shape-of-slavery/](https://pudding.cool/2017/01/shape-of-slavery/)
- Bouk, Dan. “The History and Political Economy of Personal Data over the Last Two Centuries in Three Acts.” *Osiris* 32, no. 1 (September 2017): 85–106. [https://doi.org/10.1086/693400](https://doi.org/10.1086/693400).
- David Eltis, ‘A Brief Overview of the Trans-Atlantic Slave Trade,’ Slave Voyages: The Trans-Atlantic Slave Trade Database, [https://www.slavevoyages.org/voyage/about](https://www.slavevoyages.org/voyage/about).
- Onuoha, Mimi. "The Library of Missing Datasets - MIMI ONUOHA." MIMI   ONUOHA. Accessed January 11, 2024. [https://mimionuoha.com/the-library-of-missing-datasets](https://mimionuoha.com/the-library-of-missing-datasets).
- Onuoha, Mimi. "MimiOnuoha/Missing-Datasets," January 9, 2024. [https://github.com/MimiOnuoha/missing-datasets](https://github.com/MimiOnuoha/missing-datasets).
- *The Trans-Atlantic Slave Trade Database* [https://www.slavevoyages.org/](https://www.slavevoyages.org/).
- *Freedom on the Move* [https://freedomonthemove.org/](https://freedomonthemove.org/).
- *Enslaved: Peoples of the Historical Slave Trade* [https://enslaved.org/](https://enslaved.org/)