---
title: "Classes & Comments"
toc: true
date: 2024-10-01
draft: true
---

## In-Class Agenda

- [ ] Complete Python Experience Form (Available on Canvas).
- [ ] Review optional [Scripting Python Foundations Homework](../materials/creating-curating-humanities-data/02-python-refresher-advanced/index.qmd#homework-scripting-python-foundations-optional-but-recommended).
- [ ] Review the assigned lesson on [Complex Python](../materials/creating-curating-humanities-data/03-complex-python/index.qmd)
- [ ] Start the [Introduction to Virtual Environments & Python Packages](../materials/creating-curating-humanities-data/04-virtual-environments/index.qmd).

## Assigned Materials

- Read through the [Complex Python: Classes & Comments](../materials/creating-curating-humanities-data/03-complex-python/index.qmd). Try your best to understand the material, but don't worry if you don't understand everything. We will go over it in class.

## Assignments

### Individual

- [ ] [Scripting Python Foundations Homework](../materials/creating-curating-humanities-data/02-python-refresher-advanced/index.qmd#homework-scripting-python-foundations-optional-but-recommended).

### Group
