---
title: "Scrape On & Off"
subtitle: "How do we start scaling culture as data?"
toc: true
date: 2026-03-05
---

## In-Class Agenda

- [ ] Finish discussion of [virtual environments](../materials/creating-curating-humanities-data/04-virtual-environments.qmd)
- [ ] Review questions from [Command Line Data Curation Homework](../materials/creating-curating-humanities-data/04-virtual-environments.qmd#homework-command-line-data-curation).
- [ ] Discuss assigned reading and start the [Introduction to Web Scraping](../materials/creating-curating-humanities-data/05-web-scraping.qmd) lesson.

## Assigned Materials

- Ceglowski, Maciej. "Website Obesity." *Idle Words*, October 29, 2015. [https://idlewords.com/talks/website_obesity.htm](https://idlewords.com/talks/website_obesity.htm).

## Additional Materials

- Anderson, Hanah, and Matt Daniels. "The Largest Analysis of Film Dialogue by Gender, Ever." *The Pudding*, April 2016. [https://pudding.cool/2017/03/film-dialogue/index.html](https://pudding.cool/2017/03/film-dialogue/index.html).

## Assignments

### Individual

- Optional [Python Scripting Foundations Homework](../materials/creating-curating-humanities-data/02-python-refresher-advanced.qmd#homework-scripting-python-foundations-optional-but-recommended)

### Group
