---
title: "Curating vs. Cleaning"
toc: true
date: 2024-10-15
draft: true
---

## In-Class Agenda

- [ ] Discuss and demo the remainder of the [Advanced Web Scraping Section](../materials/creating-curating-humanities-data/05-web-scraping/index.qmd#advanced-web-scraping). You are welcome to read this material prior to class but it is not required.
- [ ] Discuss assigned readings
- [ ] Time permitting: Group presentations for the [Proprietary & Perspectival Data Creation Assignment](../proprietary-perspectival-dataset-creation/index.qmd). These may get moved to the next class on Thursday if we run out of time.

## Assigned Materials

- Rawson, Katie, and Trevor Munoz. "Against Cleaning." In *Debates in the Digital Humanities 2019*, edited by Matthew K. Gold and Lauren F. Klein, 279-92. University of Minnesota Press, 2019. [https://dhdebates.gc.cuny.edu/read/untitled-f2acf72c-a469-49d8-be35-67f9ac1e3a60/section/07154de9-4903-428e-9c61-7a92a6f22e51#ch23](https://dhdebates.gc.cuny.edu/read/untitled-f2acf72c-a469-49d8-be35-67f9ac1e3a60/section/07154de9-4903-428e-9c61-7a92a6f22e51#ch23).
- Krause, Eunice. "Data Biographies: Getting to Know Your Data." *Global Investigative Journalism Network*, March 27, 2017. [https://gijn.org/2017/03/27/data-biographies-getting-to-know-your-data/](https://gijn.org/2017/03/27/data-biographies-getting-to-know-your-data/).
- Ceglowski, Maciej. "Deep-Fried Data." *Idle Words*, September 27, 2016. [https://idlewords.com/talks/deep_fried_data.htm](https://idlewords.com/talks/deep_fried_data.htm).

We will also be discussing our [assigned reading from last class](14-scrapes-on-off.qmd#assigned-materials):

- Ceglowski, Maciej. "Website Obesity." *Idle Words*, October 29, 2015. [https://idlewords.com/talks/website_obesity.htm](https://idlewords.com/talks/website_obesity.htm).


## Additional Materials

- D'Ignazio, Catherine, and Lauren F. Klein. "On Rational, Scientific, Objective Viewpoints from Mythical, Imaginary, Impossible Standpoints." In *Data Feminism*, 73-96. The MIT Press, 2020. [https://doi.org/10.7551/mitpress/11805.003.0005](https://doi.org/10.7551/mitpress/11805.003.0005).
- Posner, Miriam. "How Did They Make That?" Miriam Posner's Blog, August 29, 2013. [https://miriamposner.com/blog/how-did-they-make-that/](https://miriamposner.com/blog/how-did-they-make-that/).
- Posner, Miriam. "Humanities Data: A Necessary Contradiction - Miriam Posner's Blog," June 25, 2015. [https://miriamposner.com/blog/humanities-data-a-necessary-contradiction/](https://miriamposner.com/blog/humanities-data-a-necessary-contradiction/).

## Assignments

### Individual

### Group

- [ ] [Proprietary & Perspectival Data Creation Assignment](../proprietary-perspectival-dataset-creation/index.qmd)
