---
title: "Standardizing Culture & Data Archeology"
subtitle: "What is infrastructure and how does it shape culture as data?"
toc: true
date: 2023-03-10
---

## In-Class Agenda

- [ ] Discuss assigned readings

## Assigned Materials

- Krause, Eunice. “Data Biographies: Getting to Know Your Data.” *Global Investigative Journalism Network*, March 27, 2017. [https://gijn.org/2017/03/27/data-biographies-getting-to-know-your-data/](https://gijn.org/2017/03/27/data-biographies-getting-to-know-your-data/).
- Lee, Benjamin. "Compounded Mediation: A Data Archaeology of the Newspaper Navigator Dataset." *Digital Humanities Quarterly* 015, no. 4 (December 7, 2021). [https://www.digitalhumanities.org/dhq/vol/15/4/000578/000578.html](https://www.digitalhumanities.org/dhq/vol/15/4/000578/000578.html).
- Explore the *Newspaper Navigator Project* [https://news-navigator.labs.loc.gov/](https://news-navigator.labs.loc.gov/).

## Additional Materials

- - Loukissas, Yanni Alexander. "Collecting Infrastructures." In *All Data Are Local: Thinking Critically in a Data-Driven Society*. The MIT Press, 2019. [https://doi.org/10.7551/mitpress/11543.001.0001](https://doi.org/10.7551/mitpress/11543.001.0001).
- Adams, Hannah Alpert. "Machine Reading the Primeros Libros." *Digital Humanities Quarterly* (2017). [http://www.digitalhumanities.org/dhq/vol/10/4/000268/000268.html](http://www.digitalhumanities.org/dhq/vol/10/4/000268/000268.html).
- Cordell, Ryan. "'Q i-jtb the Raven': Taking Dirty OCR Seriously." *Book History* (2017). [https://dx.doi.org/10.1353/bh.2017.0006.](https://dx.doi.org/10.1353/bh.2017.0006.)

## Assignments

### Individual


### Group



### Additional Links

- For those interested here is the documented dataset for *Newspaper Naviagor*: Lee, Benjamin Charles Germain, Jaime Mears, Eileen Jakeway, Meghan Ferriter, Chris Adams, Nathan Yarasavage, Deborah Thomas, Kate Zwaard, and Daniel S. Weld. "The Newspaper Navigator Dataset: Extracting Headlines and Visual Content from 16 Million Historic Newspaper Pages in Chronicling America." In *Proceedings of the 29th ACM International Conference on Information & Knowledge Management*, 3055-62. Virtual Event Ireland: ACM, 2020. [https://doi.org/10.1145/3340531.3412767](https://doi.org/10.1145/3340531.3412767).
- And here is the code for *Newspaper Navigator*: [https://github.com/LibraryOfCongress/newspaper-navigator](https://github.com/LibraryOfCongress/newspaper-navigator).
- Link to map and timeline of *Chroncling America* newspapers [https://chroniclingamerica.loc.gov/newspapers/](https://chroniclingamerica.loc.gov/newspapers/) and [https://loc.maps.arcgis.com/apps/instant/media/index.html?appid=3c6a392554d545bdb1c083348ef56458&center=-97.5126;39.6376&level=3](https://loc.maps.arcgis.com/apps/instant/media/index.html?appid=3c6a392554d545bdb1c083348ef56458&center=-97.5126;39.6376&level=3).
- The original *Beyond Words* project [https://blogs.loc.gov/thesignal/2017/09/introducing-beyond-words/](https://blogs.loc.gov/thesignal/2017/09/introducing-beyond-words/). Though it has since been retired in 2021 [https://labs.loc.gov/work/experiments/beyond-words/](https://labs.loc.gov/work/experiments/beyond-words/), you can see some of the data in the *Newspaper Navigator* GitHub repository [https://github.com/LibraryOfCongress/newspaper-navigator/tree/master/beyond_words_data](https://github.com/LibraryOfCongress/newspaper-navigator/tree/master/beyond_words_data).