---
title: "Cleaning & Curating"
subtitle: "What do we mean when we “clean” culture as data?"
toc: true
date: 2026-03-24
---

## In-Class Agenda

- [ ] Review the [Fandom Wikis and Web Scraping Homework](../materials/creating-curating-humanities-data/05-web-scraping.qmd#fandom-wikis-and-web-scraping-homework).
- [ ] Finish the remainder of [introduction to APIs and cultural data](../materials/creating-curating-humanities-data/06-getting-data-apis.qmd).
- [ ] Discuss the assigned readings

## Assigned Materials

- Rawson, Katie, and Trevor Muñoz. “Against Cleaning.” In *Debates in the Digital Humanities 2019*, edited by Matthew K. Gold and Lauren F. Klein, 279–92. University of Minnesota Press, 2019. [https://dhdebates.gc.cuny.edu/read/untitled-f2acf72c-a469-49d8-be35-67f9ac1e3a60/section/07154de9-4903-428e-9c61-7a92a6f22e51#ch23](https://dhdebates.gc.cuny.edu/read/untitled-f2acf72c-a469-49d8-be35-67f9ac1e3a60/section/07154de9-4903-428e-9c61-7a92a6f22e51#ch23).
- Posner, Miriam. “Humanities Data: A Necessary Contradiction – Miriam Posner’s Blog,” June 25, 2015. [https://miriamposner.com/blog/humanities-data-a-necessary-contradiction/](https://miriamposner.com/blog/humanities-data-a-necessary-contradiction/).
- Cegłowski, Maciej. “Deep-Fried Data.” *Idle Words*, September 27, 2016. [https://idlewords.com/talks/deep_fried_data.htm](https://idlewords.com/talks/deep_fried_data.htm).

## Additional Materials

- Posner, Miriam. “How Did They Make That?” Miriam Posner’s Blog, August 29, 2013. [https://miriamposner.com/blog/how-did-they-make-that/](https://miriamposner.com/blog/how-did-they-make-that/).
- - D’Ignazio, Catherine, and Lauren F. Klein. “On Rational, Scientific, Objective Viewpoints from Mythical, Imaginary, Impossible Standpoints.” In *Data Feminism*, 73–96. The MIT Press, 2020. [https://doi.org/10.7551/mitpress/11805.003.0005](https://doi.org/10.7551/mitpress/11805.003.0005).

### Additional Links

## Assignments

### Individual

- [ ] [Fandom Wikis and Web Scraping Homework](../materials/creating-curating-humanities-data/05-web-scraping.qmd#fandom-wikis-and-web-scraping-homework)
- [ ] [Final date to submit Initial Dataset](../assessments/03-semester-project.qmd#initial-dataset-submission)

### Group
