---
title: "Notes & Points"
toc: true
date: 2024-10-24
draft: true
---

## In-Class Agenda

- [ ] Discuss readings from Tuesday's class
- [ ] Complete refresher to [Notebooks and Pandas](../materials/interpreting-communicating-humanities-data/01-intro-notebooks/index.qmd)
- [ ] Remaining time work on Mid-Semester Dataset Update or start EDA Lesson

## Assigned Materials (From Tuesday)

- Schmidt, Benjamin M. "Do Digital Humanists Need to Understand Algorithms?" In *Debates in the Digital Humanities 2016*, edited by Matthew K. Gold and Lauren F. Klein, 546-55. University of Minnesota Press, 2016. Use the JSTOR link for PDF & Hypothesis [https://doi.org/10.5749/j.ctt1cn6thb.51](https://doi.org/10.5749/j.ctt1cn6thb.51) or use the Manifold Platform link [https://dhdebates.gc.cuny.edu/read/untitled/section/557c453b-4abb-48ce-8c38-a77e24d3f0bd](https://dhdebates.gc.cuny.edu/read/untitled/section/557c453b-4abb-48ce-8c38-a77e24d3f0bd).
- Mullen, Lincoln. "Isn't it obvious?" *lincolnmullen.com*, January 10, 2018. [https://lincolnmullen.com/blog/isnt-it-obvious/](https://lincolnmullen.com/blog/isnt-it-obvious/).
- Lincoln, Matthew. "Confabulation in the humanities." *matthewlincoln.net*, March 21, 2015. [https://matthewlincoln.net/2015/03/21/confabulation-in-the-humanities.html](https://matthewlincoln.net/2015/03/21/confabulation-in-the-humanities.html).

### Additional Links

- *The Syuzhet Package* by Matthew Jockers [https://cran.r-project.org/web/packages/syuzhet/vignettes/syuzhet-vignette.html](https://cran.r-project.org/web/packages/syuzhet/vignettes/syuzhet-vignette.html).
- Annie Swafford "Problems with the Syuzhet Package." *Anglophile in Academia:  Annie Swafford's Blog (blog)*, March 2, 2015. [https://annieswafford.wordpress.com/2015/03/02/syuzhet/](https://annieswafford.wordpress.com/2015/03/02/syuzhet/).
- Da, Nan Z. "The Computational Case against Computational Literary Studies." *Critical Inquiry* 45, no. 3 (March 2019): 601-39. [https://doi.org/10.1086/702594](https://doi.org/10.1086/702594).
- Robertson, Stephen, and Lincoln Mullen. "Arguing with Digital History: Patterns of Historical Interpretation (Annotated Version)." *Journal of Social History* 54, no. 4 (2021): 1005-22. [https://doi.org/10.31835/ma.2021.01](https://doi.org/10.31835/ma.2021.01).
- "Arguing with Digital History Working Group." Roy Rosenzweig Center for History and New Media, November 13, 2017. [https://doi.org/10.18665/sr.22532](https://doi.org/10.18665/sr.22532).
- Mullen, Lincoln A. *America's Public Bible: A Commentary*. Stanford University Press, 2023. [https://americaspublicbible.supdigital.org](https://americaspublicbible.supdigital.org).
- Ramsay, Stephen. *Reading Machines: Toward an Algorithmic Criticism*. University of Illinois Press, 2011. [https://www.jstor.org/stable/10.5406/j.ctt1xcmrr](https://www.jstor.org/stable/10.5406/j.ctt1xcmrr).

## Additional Materials

- Broman, Karl W., and Kara H. Woo. "Data Organization in Spreadsheets." *American Statistician* 72, no. 1 (2018): 2-10. [https://doi.org/10.1080/00031305.2017.1375989](https://doi.org/10.1080/00031305.2017.1375989).
- Gebru, Timnit, et al. "Datasheets for Datasets." *Communications of the ACM* 64, no. 12 (November 19, 2021): 86-92. [https://doi.org/10.1145/3458723](https://doi.org/10.1145/3458723).
