---
title: "Making A Point"
toc: true
date: 2024-10-29
draft: true
---

## In-Class Agenda

- [ ] Review the [GETing Culture Across APIs Homework](../materials/creating-curating-humanities-data/06-getting-data-apis.qmd#getting-culture-across-apis-homework).
- [ ] Continue refresher to [Notebooks and Pandas](../materials/interpreting-communicating-humanities-data/01-intro-notebooks.qmd).
- [ ] Start introduction to [EDA and Data Visualization](../materials/interpreting-communicating-humanities-data/02-eda-data-viz.qmd).

## Additional Materials

- Davis, Erin. "What physical traits are most tied to gender in literature? Eye roll: Women are all soft thighs and red lips." *The Pudding*, July 2020. [https://pudding.cool/2020/07/gendered-descriptions/](https://pudding.cool/2020/07/gendered-descriptions/).
- Wu, Shirley. "An Interactive Visualization of Every Line in Hamilton." *The Pudding*, March 2017. [https://pudding.cool/2017/03/hamilton.html](https://pudding.cool/2017/03/hamilton.html).

## Assignments

### Individual

- [ ] Complete the [GETing Culture Across APIs Homework](../materials/creating-curating-humanities-data/06-getting-data-apis.qmd#getting-culture-across-apis-homework) by the next class.

### Group

- [ ] [Mid-Semester Dataset and Documentation Update](../assessments/03-semester-project.qmd#mid-semester-dataset-and-documentation-update-15).

## Assigned Materials

- Schmidt, Benjamin M. "Do Digital Humanists Need to Understand Algorithms?" In *Debates in the Digital Humanities 2016*, edited by Matthew K. Gold and Lauren F. Klein, 546-55. University of Minnesota Press, 2016. Use the JSTOR link for PDF & Hypothesis [https://doi.org/10.5749/j.ctt1cn6thb.51](https://doi.org/10.5749/j.ctt1cn6thb.51) or use the Manifold Platform link [https://dhdebates.gc.cuny.edu/read/untitled/section/557c453b-4abb-48ce-8c38-a77e24d3f0bd](https://dhdebates.gc.cuny.edu/read/untitled/section/557c453b-4abb-48ce-8c38-a77e24d3f0bd).
- Mullen, Lincoln. "Isn't it obvious?" *lincolnmullen.com*, January 10, 2018. [https://lincolnmullen.com/blog/isnt-it-obvious/](https://lincolnmullen.com/blog/isnt-it-obvious/).
- Lincoln, Matthew. "Confabulation in the humanities." *matthewlincoln.net*, March 21, 2015. [https://matthewlincoln.net/2015/03/21/confabulation-in-the-humanities.html](https://matthewlincoln.net/2015/03/21/confabulation-in-the-humanities.html).

## Additional Materials

- Koeser, Rebecca Sutton. "Trusting Others to 'Do the Math.'" *Interdisciplinary Science Reviews* 40, no. 4 (2015): 376-392. [https://doi.org/10.1080/03080188.2016.1165454](https://doi.org/10.1080/03080188.2016.1165454).
- Weingart, Scott B. "Argument Clinic." *scottbot.net*, July 26, 2017. [https://scottbot.net/argument-clinic/](https://scottbot.net/argument-clinic/).
- Thomas, Amber. *Shaping Ideas into Data Stories* [Speaker Series w/ Amber Thomas from The Pudding], 2020. [https://www.youtube.com/watch?v=J3Awc4HxDK0](https://www.youtube.com/watch?v=J3Awc4HxDK0).

### Additional Links

- *The Syuzhet Package* by Matthew Jockers [https://cran.r-project.org/web/packages/syuzhet/vignettes/syuzhet-vignette.html](https://cran.r-project.org/web/packages/syuzhet/vignettes/syuzhet-vignette.html).
- Annie Swafford "Problems with the Syuzhet Package." *Anglophile in Academia:  Annie Swafford's Blog (blog)*, March 2, 2015. [https://annieswafford.wordpress.com/2015/03/02/syuzhet/](https://annieswafford.wordpress.com/2015/03/02/syuzhet/).
- Da, Nan Z. "The Computational Case against Computational Literary Studies." *Critical Inquiry* 45, no. 3 (March 2019): 601-39. [https://doi.org/10.1086/702594](https://doi.org/10.1086/702594).
- Robertson, Stephen, and Lincoln Mullen. "Arguing with Digital History: Patterns of Historical Interpretation (Annotated Version)." *Journal of Social History* 54, no. 4 (2021): 1005-22. [https://doi.org/10.31835/ma.2021.01](https://doi.org/10.31835/ma.2021.01).
- "Arguing with Digital History Working Group." Roy Rosenzweig Center for History and New Media, November 13, 2017. [https://doi.org/10.18665/sr.22532](https://doi.org/10.18665/sr.22532).
- Mullen, Lincoln A. *America's Public Bible: A Commentary*. Stanford University Press, 2023. [https://americaspublicbible.supdigital.org](https://americaspublicbible.supdigital.org).
- Ramsay, Stephen. *Reading Machines: Toward an Algorithmic Criticism*. University of Illinois Press, 2011. [https://www.jstor.org/stable/10.5406/j.ctt1xcmrr](https://www.jstor.org/stable/10.5406/j.ctt1xcmrr).