---
title: "How do we tell stories at scale?" 
subtitle: "Scrolls & Hovers"
toc: true
date: 2026-04-02
---

## In-Class Agenda

- [ ] Review the [GETing Culture Across APIs Homework](../materials/creating-curating-humanities-data/06-getting-data-apis.qmd#getting-culture-across-apis-homework).
- Start the introduction to [advanced EDA & data visualization](../materials/interpreting-communicating-humanities-data/02-eda-data-viz.qmd). Slides available [here](../slides/15-eda-data-viz.qmd).

## Assigned Materials


## Additional Materials

- Samora, Russell. “Life After Death on Wikipedia.” *The Pudding*, August 2018. [https://pudding.cool/2018/08/wiki-death/](https://pudding.cool/2018/08/wiki-death/). 
- Anderson, Hanah, and Matt Daniels. “The Largest Analysis of Film Dialogue by Gender, Ever.” *The Pudding*, April 2016. [https://pudding.cool/2017/03/film-dialogue/index.html](https://pudding.cool/2017/03/film-dialogue/index.html). 

## Assignments

### Individual

- [ ] Complete the [GETing Culture Across APIs Homework](../materials/creating-curating-humanities-data/06-getting-data-apis.qmd#getting-culture-across-apis-homework).

### Group
