---
title: "Augmentation & AI"
toc: true
date: 2024-11-14
draft: true
---

## In-Class Agenda

- [ ] Discuss assigned readings and explore demo of LLMs for data work (links below).
- [ ] Groups present their [Computing Cultural Data Assignment](../computing-cultural-data/index.qmd).

## Assigned Materials

- Underwood, Ted. "Can Language Models Predict the next Twist in a Story?" *The Stone and the Shell* (blog), January 5, 2024. [https://tedunderwood.com/2024/01/05/can-language-models-predict-the-next-twist-in-a-story/](https://tedunderwood.com/2024/01/05/can-language-models-predict-the-next-twist-in-a-story/).
- Samora, Russell, and Michelle Pera-McGhee. "We Had an AI Attempt to Make a Data-Driven Story like We Do at The Pudding." *The Pudding*, July 2024. [https://pudding.cool/2024/07/ai](https://pudding.cool/2024/07/ai).

## Additional Materials

- Underwood, Ted. "Machine Learning and Human Perspective." *PMLA* [https://www.ideals.illinois.edu/handle/2142/109140](https://www.ideals.illinois.edu/handle/2142/109140).
- McGrath, Laura B. "Charisma (Embodiment): a Response to Tess McNulty." *Post45* (2019) [https://post45.org/2019/05/charisma-embodiment-a-response-to-tess-mcnulty/](https://post45.org/2019/05/charisma-embodiment-a-response-to-tess-mcnulty/).
- Lee, Benjamin Charles Germain. "The 'Collections as ML Data' Checklist for Machine Learning and Cultural Heritage." *Journal of the Association for Information Science and Technology* (2023). [https://doi.org/10.1002/asi.24765](https://doi.org/10.1002/asi.24765).
- Bender, Emily M., et al. "On the Dangers of Stochastic Parrots: Can Language Models Be Too Big?" *Proceedings of the 2021 ACM Conference on Fairness, Accountability, and Transparency* (FAccT '21), 2021, 610-623. [https://doi.org/10.1145/3442188.3445922](https://doi.org/10.1145/3442188.3445922).

### Additional links

- AI for Humanists Project [https://aiforhumanists.com/](https://aiforhumanists.com/)
- Copied notebook from AI for Humanists with our novels data available [here](https://colab.research.google.com/drive/1VnZNIBjPPInfGnOUCye1QZ_5N6xTIfSO?usp=sharing)
- [Additional local notebooks using Classification Models & LLMs](../assets/files/is310IntroLLMs.ipynb). Be sure to install the necessary Python libraries into your virtual environment as well.

## Assignments

### Individual

### Group

- [ ] Complete group assignment on [Computing Cultural Data](../computing-cultural-data/index.qmd).
