---
title: "Reproducibility & Responsibility"
toc: true
date: 2024-11-19
draft: true
---

## In-Class Agenda

- [ ] Continue remaining group presentations for [Computing Cultural Data Assignment](../computing-cultural-data/index.qmd).
- [ ] Discuss the assigned readings

## Assigned Materials (Now for Thursday November 21)

- Nowviskie, Bethany. "Reconstitute the World." Bethany Nowviskie, June 12, 2018. [http://nowviskie.org/2018/reconstitute-the-world/](http://nowviskie.org/2018/reconstitute-the-world/).
- Ding, Jennifer, Jan Diehm, and Michelle McGhee. "Can Data Die? Tracking the Lenna Image." *The Pudding*, October 2021. [https://pudding.cool/2021/10/lenna/](https://pudding.cool/2021/10/lenna/).

## Additional Materials

- Klein, Lauren F., and Sandeep Soni. "How Words Lead to Justice." *Public Books*, August 17, 2021. [https://www.publicbooks.org/how-words-lead-to-justice/](https://www.publicbooks.org/how-words-lead-to-justice/).

### Additional Links

- *Collections As Data* Project [https://collectionsasdata.github.io/](https://collectionsasdata.github.io/)
- Padilla, Thomas, Scates Kettler, Hannah, Varner, Stewart, & Shorish, Yasmeen.(2023).*Vancouver Statement on Collections as Data*.Zenodo. [https://zenodo.org/records/8342171](https://zenodo.org/records/8342171).

## Assignments

### Individual

### Group

- [ ] [Experimenting With Datasets Update](../assessments/03-semester-project/index.qmd#experimenting-with-datasets-update-5).
