---
title: "Preservation & Publics"
toc: true
date: 2024-11-21
draft: true
---

## In-Class Agenda

- [ ] Complete remainder of Group 2 and Group 6 presentations for [Computing Cultural Data Assignment](../computing-cultural-data/index.qmd).
- [ ] Discuss the assigned readings from Tuesday, [available here](25-reproducibility-responsibility.qmd#assigned-materials) and the ones from today.
- [ ] Discuss final project submissions and work on final projects.

## Assigned Materials

- D'Ignazio, Catherine, and Lauren F. Klein. "Show Your Work." In *Data Feminism*. The MIT Press, 2020. [https://direct.mit.edu/books/book/4660/chapter/213292/Show-Your-Work](https://direct.mit.edu/books/book/4660/chapter/213292/Show-Your-Work). This is a PDF reading so if you want to use Hypothesis to annotate, you will need to open your local version of the PDF in your browser. For help, please refer to our [Hypothesis guide](../materials/introducing-humanities-computing/01-course-tools/index.qmd#using-hypothesis-on-local-pdfs).
- Skim and explore this online book from The Turing Way Community. (2022). *The Turing Way: A handbook for reproducible, ethical and collaborative research* (1.0.2). Zenodo. DOI 10.5281/zenodo.3233853. **Come to class with at least one question or idea from the book that you think might be relevant to your final project**. [https://book.the-turing-way.org/](https://book.the-turing-way.org/).


## Additional Materials

- Posner, Miriam. "JavaScript Is for Girls." *Logic(s) Magazine*, March 15, 2017. [https://logicmag.io/intelligence/javascript-is-for-girls/](https://logicmag.io/intelligence/javascript-is-for-girls/).
- Dombrowski, Quinn. "Minimizing Computing Maximizes Labor." *Digital Humanities Quarterly* 016, no. 2 (June 25, 2022).
- Kinnaman, Alex, and Corinne Guimont. "DH as Data: Establishing Greater Access through Sustainability." *Digital Humanities Quarterly* 017, no. 3 (August 24, 2023). [https://www.digitalhumanities.org/dhq/vol/17/3/000715/000715.html](https://www.digitalhumanities.org/dhq/vol/17/3/000715/000715.html).

### Additional Links

- *Collections As Data* Project [https://collectionsasdata.github.io/](https://collectionsasdata.github.io/)
- Padilla, Thomas, Scates Kettler, Hannah, Varner, Stewart, & Shorish, Yasmeen.(2023).*Vancouver Statement on Collections as Data*.Zenodo. [https://zenodo.org/records/8342171](https://zenodo.org/records/8342171).
- Clement, Tanya E., Douglas Reside, Brian Croxall, Julia Flanders, Neil Fraistat, Steve Jones, Matt Kirschenbaum, et al. "Collaborators' Bill of Rights," 2021. [https://doi.org/10.17613/mvar-kj35](https://doi.org/10.17613/mvar-kj35).
