---
title: 'Schedule & Assignments Overview'
toc: true
---

::: {.callout-note}
This schedule is subject to change depending on our collective progress this semester, so please treat this as a general guideline that is not set in stone. I will add assignments as we progress below, but you should generally expect to have both assigned materials and assignments each week.
:::

## Weekly Schedule

This overview gives a top level view of the topics for each of our meetings. You can either use the side navigation or click on a topic to jump to that section.

| Tuesday Topics (Explorations)  | Thursday Topics (Experimentations) |
| -----------------: | --------------: |
| [January 20 - Why Represent Culture As Data? Introducing Computing in the Humanities & Culture As Data](01-introducing-computing-in-the-humanities-culture-as-data.qmd) | [January 22 - How Will We Work in This Course? Programming & Processing](02-programming-and-processing.qmd) |
| [January 27 - What does it mean to work with culture as data responsibly, and how does this change across disciplines and industries? Responsible Computing of Culture & Contextualizing Social Knowledge](03-responsible-computing-of-culture-and-contextualizing-social-knowledge.qmd) | [January 29 - How can we work collaboratively and computationally? Version & File Histories](04-version-file-histories.qmd) |
| [February 3 - How and when did we first start representing culture as data? Histories of Culture & Computing](05-histories-culture-computing.qmd) | [February 5 - What does it mean to work digitally? Markup & Markdown](06-markup-and-markdown.qmd) |
| [February 10 - What are the historic legacies and politics of representing culture as data? Digital Objects & Obsolescence](07-digital-objects-and-obsolescence.qmd) | [February 12 - How has the web changed culture as data? Servers & Web Standards](08-servers-web-standards.qmd) |
| [February 17 - Who decides what culture becomes data? Archives & Collections](09-archives-collections.qmd) | [February 19 - How can we represent culture computationally? Scripts & Types](10-scripts-types.qmd) |
| [February 24 - How do our choices shape whose culture becomes data? Data Feminism & Design Justice](11-data-feminism-design-justice.qmd) | [February 26 - How can we start creating culture as data? Ecosystems & Environments](12-ecosystems-environments.qmd) |
| [March 3 - How do we ethically and legally work with culture as data? Terms & Traps](13-terms-traps.qmd) | [March 5 - How do we start scaling culture as data? Scrape On & Off](14-scrapes-structures.qmd) |
| [March 10 - What is infrastructure and how does it shape culture as data? Standardizing Culture & Data Archeology](15-standardizing-culture-data-archeology.qmd) | [March 12 - How do we get culture as data? Interfaces & Limits](16-interfaces-limits.qmd) |
| March 17 & 19 - Spring Break | |
| [March 24 - What do we mean when we “clean” culture as data? Cleaning & Curating](17-cleaning-curating.qmd) | [March 26 - How do we work at scale with culture at data? Patterns & Outliers](18-patterns-outliers.qmd) |
| [March 31 - How do we tell stories about culture with data? Arguments & Plots](19-arguments-plots.qmd) | [April 2 - How do we tell stories at scale? Scrolls & Hovers](20-scrolls-hovers.qmd) |
| [April 7 - How do we build trust with culture as data? Networks & Names](21-networks-names.qmd) | [April 9 - How can computation augment culture as data? Texts & Tokens](22-texts-tokens.qmd) |
| [April 14 - How are new technologies shaping culture as data? Augmentation & AI](23-augmentation-ai.qmd) | [April 16 - How can we responsibly use AI for culture as data? Speculations & Classifications](24-speculations-classifications.qmd) |
| [April 21 - How can we preserve culture as data? Publics & Principles](25-publics-principles.qmd) | [April 23 - How do we document culture as data? Sheets & Cards](26-sheets-cards.qmd) |
| [April 28 - What don’t we know about culture as data? Questions & Revisions](27-questions-revisions.qmd.qmd) | [April 30 - What are the future directions for culture as data? Presentations & Demonstrations](28-future-directions-presentations-demonstrations.qmd) | [May 5 - What are the horizons for culture as data? Presentations & Demonstrations](29-future-horizons-final-projects.qmd) |

## Assignment Schedule

*Assignments will be added throughout the semester depending on how much material we get through.*

### Individual Assignments

| Assignment | Due Date (Subject to Change) |
| -----------------: | --------------: |
| Initial Interest Survey (Link Available on Canvas) | [Due by Midnight CT on January 21](03-responsible-computing-of-culture-and-contextualizing-social-knowledge.qmd) |
| [Init IS310 Homework](../materials/introducing-humanities-computing/03-intro-versioning.qmd#homework-init-is310) | [Due by Midnight CT on January 28](04-version-file-histories.qmd) |
| [Lost & Found in the Cultural Command Line Homework](../materials/introducing-humanities-computing/06-intro-file-formats.qmd#homework-lost-found-in-the-cultural-command-line) | [Due by Midnight CT on February 4](06-markup-and-markdown.qmd) |
| [Source & Style Homework](../materials/introducing-humanities-computing/07-intro-html.qmd#homework-source-and-style) | [Due By Midnight CT on February 11](08-servers-web-standards.qmd) |
| [Doing It Live Homework](../materials/introducing-humanities-computing/08-intro-web.qmd#assignment-doing-it-live) | [Due By Midnight CT on February 23](11-data-feminism-design-justice.qmd) |
| [OPTIONAL Scripting Python Foundations](../materials/creating-curating-humanities-data/02-python-refresher-advanced.qmd#homework-scripting-python-foundations-optional-but-recommended) | [Due by Midnight CT on March 4](14-scrapes-structures.qmd) |
| [Command Line Data Curation Homework](../materials/creating-curating-humanities-data/04-virtual-environments.qmd#homework-command-line-data-curation) | [Due By Midnight CT on March 11](16-interfaces-limits.qmd) | 
| [Fandom Wikis and Web Scraping Homework](../materials/creating-curating-humanities-data/05-web-scraping.qmd#fandom-wikis-and-web-scraping-homework) | [Due By Midnight CT on March 23](17-cleaning-curating.qmd) |
| [GETting Culture Across APIs Homework](../materials/creating-curating-humanities-data/06-getting-data-apis.html#getting-culture-across-apis-homework) | [Due By Midnight CT on April 1](20-scrolls-hovers.qmd) |

### Group Assignments

| Assignment | Due Date (Subject to Change) |
| -----------------: | --------------: |
|[Collective & Individual Topic Selection](../assessments/03-semester-project.qmd#collective-individual-topic-selection) | [Due February 5 with Optional Extension Until February 12](06-markup-and-markdown.qmd) |
|[Mass Digitization & Digital Libraries Group Assignment](../assessments/06-collecting-digitizing-culture.qmd) | Due February 10 & 12 In-Class Presentations |