---
title: Weekly Assessments 50%
toc: true
---


Your performance in weekly assessments constitutes half of your final grade. These assessments include engaging with assigned materials through in-class discussions, asynchronous annotations of assigned materials, and weekly coding assignments, all of which is detailed below. **Weekly assessments are graded as pass/fail though part of that assessment is also your degree of engagement and creativity, as well as the growth you demonstrated throughout the semester.**

## Weekly Participation (25%)

Weekly participation includes both individual engagement with course materials and collaborative group presentations. This combination ensures you are both deepening your own understanding and learning from your peers’ when working with culture as data.

### Weekly Seminar Discussion and Asynchronous Annotations 15%

Before each class, you're expected to engage with assigned materials, ranging from reading a book chapter or article, to exploring a data visualization to reading documentation. These materials lay the groundwork for our class discussions, as well as helping you with your semester long project. There may be some weeks that are of more interest to you, and I encourage you to explore the additional listed materials, though these are optional.

Questions to consider when engaging with the weekly materials include:

- What is the main argument of this piece? Is there an argument? What is interesting or evocative or infuriating?
- If there is an argument, how does the author support the argument? What sorts of evidence or data did they utilize? How did they organize the structure of their piece?
- If you didn't feel there was an argument, what do you think was the author's purpose or goal with the material (whether a project, blog post, tool, etc...)?
- What is the likely audience for the material?
- What connections or tensions did you identify across materials?
- What did you not understand in the materials? What was confusing?
- How would you connect the week's materials to previous ones?

Overall, remember the goal is not to detail everything the author or creator says, but instead try to summarize in a few lines their central points and how they relate to the other materials from that week.

One way to **demonstrate your engagement with the weekly materials is to participate in our weekly seminar discussions**. Your contributions could be in the form of questions about complex or confusing concepts in the readings, connections that you want to share across the assigned materials, or feedback and responding to peer contributions. More than simply talking as much as possible though, our goal with seminar discussions is to create a thoughtful and respectful intellectual community.

The other way to **demonstrate engagement is through asynchronous annotation**s. We will be using the Hypothesis annotation platform, with an introductory session in the first week of class. These annotations are a space for you to share your thoughts on the week's materials and engage with your peers, and you will occasionally be asked to expand on your annotations during our discussions. You can sign up for Hypothesis here [hypothes.is/signup](hypothes.is/signup) and join our collective group (link in the syllabus or on Canvas). You will need to install the Hypothesis Browser Extension for your preferred browser as well.

#### Grading Policy

For weekly seminar discussions, you **must both be in person in class and be an active participant in the discussion or activities to receive full credit**. Simply attending class is not enough; you are expected to contribute thoughtfully to discussions and engage with the material and your peers.

For the weekly annotations, you need to **submit these via Hypothesis by midnight the day before class**. This ensures that your contributions are available for others to review and discuss during our seminar. Your annotations should be tagged appropriately in our Hypothesis group to facilitate organization and discussion. **To receive full credit, annotations must demonstrate thoughtful engagement with the material**—this includes summarizing key points, raising questions, and making connections with other readings or topics we've covered.

### Group Presentations and Collaboration (10%)

Groups will be assigned within the first two weeks of class after an initial survey of student interests and backgrounds (e.g., music, literature, social media, gaming) . This group will work together to complete active in-class activities and out-of-class assignments, which will be documented and submitted via GitHub. 

**Structure and Expectations:**

- **Weekly Prompts and Activities:** Each week, your group will be assigned a prompt or task that builds on the week’s materials. This could involve finding digital objects, exploring datasets, or applying a concept from the readings.
- **In-Class Presentations:** Some weeks, your group will present your findings to the class. Not every group will present every week, but even when your group is not presenting, you are still expected to submit your work to GitHub and be prepared to discuss it if called upon. Presentations should be clear, concise, and demonstrate your group’s understanding and application of the week’s materials
- **Documentation and Submission:** All group work, whether presented in class or not, must be documented and submitted to your group’s GitHub repository. This documentation should include a summary of your group’s activities, details on how the labor was divided, and any relevant reflections on the process. Clear and detailed documentation is crucial for both grading and for your group members' progress on the semester-long project.

#### Grading Policy

Your grade for weekly group work will be based on your active participation in presentations, the quality of your contributions, and the effectiveness of your collaboration. This includes both in-class activities and the quality of the work submitted on GitHub. This grade will not be impacted if a member of your group is absent, though the group will be required to pivot their schedule and plan in that event.

Weekly group work **must be submitted to GitHub by midnight prior to the class when it is due.** This ensures that the work is available for review and that all group members are accountable for their contributions. **Late submissions will receive half credit, as long as they are accompanied by an explanation for the delay. Repeated late submissions will result in the group meeting with the Instructor.**

### Weekly Coding Assignments 25%

You will also have weekly programming assignments to complete and share via GitHub, unless indicated otherwise. Most coders work collaboratively, often engaging in pair programming, a method of talking through code problems together. This course encourages you to pair program, and work together to learn from each other's solutions. However, be aware that copying and pasting code might get you through one week, but the concepts in this course move quickly and build upon each other. So, I would encourage you to do your best to not only try and complete the assignments each week, but to ensure that you are understanding the core concepts.. Questions are encouraged both in person and online, and we will be discussing more about best coding practices during our first week.

#### Grading Policy

Weekly coding assignments **must be submitted via GitHub by midnight prior to the class meeting when they are due**. These assignments are an opportunity to practice and solidify your understanding of the concepts covered each week. **Late submissions will be accepted but will only receive half credit, as long as they are turned in before the final class meeting**. Pair programming is encouraged, but remember that understanding the underlying concepts is crucial as the material builds progressively throughout the semester.

## Required Texts and Resources

Almost all the course materials will be available online through either the course website or Canvas, so you are not required to purchase any materials. Throughout the semester, I will highlight books that you may want to purchase but that is completely up to you. The same goes for our coding resources. You will not be required to purchase any software but you will need access to a computer, so please let me know early on if you think that will be an issue and we can try and find solutions.

