---
title: "Assigned Project Groups"
toc: true
---

After completing the initial interest survey, each student has been placed into a group with which they will work on a project for the remainder of the semester. These groups were created based on the interests and skills that students indicated in the survey, and we have endeavored to ensure everyone is in a group that aligns with their top choices.

You will find your group number and members below, as well as link to your GitHub repository for the semester long project. I have included in the initial `README.md` file some initial potential cultural interest topics that you might consider for your project. However, I want to stress that this is a **suggested** focus based off of your survey responses. You should discuss this further as a group, and you are welcome to choose a different topic if you all agree. If you cannot find a clear common interest, I would encourage you to reach out to the Instructors and also consider if there is a broad overarching theme that might provide some structure, while still allowing for individual interests to be pursued.

If you do not have a group, please fill out the initial interest survey as soon as possible so that we can place you in a group. If you have any questions or concerns about your group placement, please reach out to the Instructors as soon as possible.

The instructors will be adding you to the following GitHub repositories in the next week as you submit your first assignments and share your GitHub usernames with us.

**Please note that these groupings are tentative and subject to change in the first few weeks. As a reminder, no group will be penalized if members leave and the instructors will help them pivot and adapt to any unforeseen changes.**

The groups are as follows:

1. **Group 1** SPORTS
   - [GitHub Repository](https://github.com/CultureAsData-UIUC/is310-spring-2026-group-1)
   - Members:
       - Adam O.
       - Colin B.
       - Maya B.
       - Alex T.
       - Tiffany C.
       

2. **Group 2** GAMING
   - [GitHub Repository](https://github.com/CultureAsData-UIUC/is310-spring-2026-group-2)
   - Members:
       - Anshuman S.
       - Charles C.
       - Hongli P.
       - Jesus V.
       - Andrew P.

3. **Group 3** MUSIC & SOCIAL MEDIA
   - [GitHub Repository](https://github.com/CultureAsData-UIUC/is310-spring-2026-group-3)
   - Members:
        - Ananya S.
        - Eshaan A.
        - Beau L.
        - Inika S.
        - Rohan V.G.
        - Raymond Z.

4. **Group 4** FILMS & FOOD & SOCIAL MEDIA
   - [GitHub Repository](https://github.com/CultureAsData-UIUC/is310-spring-2026-group-4)
   - Members:
        - Diara S.
        - Flynn H.
        - Maya B.
        - Rana B.
        - Solam S.
        - Michelle Y.
        - Cynthia S.


5. **Group 5** ACADEMICS & INTERNET CULTURE
   - [GitHub Repository](https://github.com/CultureAsData-UIUC/is310-spring-2026-group-5)
   - Members:
        - Diana N.
        - Emily C.
        - Zohra H.
        - Hannen O.
        - Malvika C.
        - Tara V.

6. **Group 6** POLITICS & HISTORY
   - [GitHub Repository](https://github.com/CultureAsData-UIUC/is310-spring-2026-group-6)
   - Members:
        - Ananya K.
        - Christina J.
        - Jasmitha G.
        - Vedha P.
        - Daria M.
        - Adin F.
